name: kortex_pour

task_name: pour

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    image:
        shape: [3, 84, 84]
        type: rgb
    agent_pos:
      shape: [10]
      type: low_dim
  action:
    shape: [10]

env_runner: null
  # _target_: diffusion_policy_3d.env_runner.base_runner.KortexRunner
  # max_steps: 5000
  # n_obs_steps: ${n_obs_steps}
  # n_action_steps: ${n_action_steps}
  # fps: 10
  # task_name: pour

dataset:
  _target_: diffusion_policy_3d.dataset.kortex_dataset.KortexDataset
  zarr_path: data/kortex_data/pour.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
