name: kortex_cut

task_name: cut

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    image:
        shape: [3, 84, 84]
        type: rgb
    agent_pos:
      shape: [10]
      type: low_dim
  action:
    shape: [10]

env_runner:

dataset:
  _target_: diffusion_policy_3d.dataset.kortex_dataset.KortexDataset
  zarr_path: data/kortex_data/cut_10.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
